version: "1"
rules:
  - base: master
    upstream: plausible:master
    mergeMethod: merge
    mergeUnstable: false
    assignees:
      - mfydev
    reviewers:
      - mfydev
    conflictReviewers:
      - mfydev
label: ":arrow_heading_down: pull"
conflictLabel: "merge-conflict"